### ISSUE TITLE
printing not functioning on macos

### ISSUE THREAD

**Issue by Ali-Razmjoo** [zdresearch/OWASP-Honeypot#40] opened 2019-06-21 13:29 UTC
when I run `python ohp.py -m ssh/strong_password, honeypot is working without any output, tested on python3.7 osx. not even ohp logo is printing.

**Comment by dhirensr** [comment] 2020-02-23 12:19
@Ali-Razmjoo : let's close this ticket if the issue is fixed!

**Closed** 2020-02-23 15:00 UTC
Labels: bug
